services:
  - type: web
    name: nova-academy
    runtime: static

    buildCommand: npm install && npm run build

    staticPublishPath: dist/app/browser

    envVars:
      - key: NODE_ENV
        value: production

      - key: GROQ_API_KEY
        sync: false

      - key: GROQ_EVAL_KEY
        sync: false

      - key: GROQ_GEN_KEY
        sync: false
